### ISSUE TITLE
Radiation test problems don't compile with current version of Hypre

### ISSUE THREAD

**Issue by ChrisDeGrendele** [AMReX-Astro/Castro#372]
The radiation test problems .../Castro/Exec/radiation_tests/  do not compile using the current version of Hypre. The problems do compile with Version 2.10.

Here's the error message using version 2.11:

networks -I../../../Microphysics/networks/general_null -I/home/cdegrendele/codes/Microphysics/EOS -I/home/cdegrendele/codes/Microphysics/networks -I../../../Microphysics/opacity/null -I/home/cdegrendele/codes/AMReX/Tools/C_scripts -c ../../../Source/radiation/HypreExtMultiABec.cpp -o tmp_build_dir/o/1d.gnu.MPI.EXE/HypreExtMultiABec.o
../../../Source/radiation/HypreExtMultiABec.cpp:197:46: error: macro "hypre_CTAlloc" requires 3 arguments, but only 2 given
       mat = hypre_CTAlloc(double, size*volume);
                                              ^
../../../Source/radiation/HypreExtMultiABec.cpp:245:51: error: macro "hypre_CTAlloc" requires 3 arguments, but only 2 given
       Real *mat_tmp = hypre_CTAlloc(double, volume);
                                                   ^
../../../Source/radiation/HypreExtMultiABec.cpp:253:26: error: macro "hypre_TFree" requires 2 arguments, but only 1 given
       hypre_TFree(mat_tmp);
                          ^
../../../Source/radiation/HypreExtMultiABec.cpp:256:22: error: macro "hypre_TFree" requires 2 arguments, but only 1 given
       hypre_TFree(mat);
                      ^
../../../Source/radiation/HypreExtMultiABec.cpp: In member function ‘virtual void HypreExtMultiABec::loadMatrix()’:
../../../Source/radiation/HypreExtMultiABec.cpp:197:13: error: ‘hypre_CTAlloc’ was not declared in this scope
       mat = hypre_CTAlloc(double, size*volume);
             ^~~~~~~~~~~~~
../../../Source/radiation/HypreExtMultiABec.cpp:197:13: note: suggested alternative: ‘hypre_CAlloc’
       mat = hypre_CTAlloc(double, size*volume);
             ^~~~~~~~~~~~~
             hypre_CAlloc
../../../Source/radiation/HypreExtMultiABec.cpp:253:7: error: ‘hypre_TFree’ was not declared in this scope
       hypre_TFree(mat_tmp);
       ^~~~~~~~~~~
../../../Source/radiation/HypreExtMultiABec.cpp:253:7: note: suggested alternative: ‘hypre_Free’
       hypre_TFree(mat_tmp);
       ^~~~~~~~~~~
       hypre_Free
